// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6yzfr5TO8RrPHCsKH2PPaERnUFNsOfZA',
    appId: '1:165374914153:web:46402ebf054648e7f2fcf8',
    messagingSenderId: '165374914153',
    projectId: 'todo-app-project-e81a3',
    authDomain: 'todo-app-project-e81a3.firebaseapp.com',
    storageBucket: 'todo-app-project-e81a3.appspot.com',
    measurementId: 'G-XBMWMV4SRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Ikqw7I6cAH3l-AmE2o2qAnx2jhPQ_WI',
    appId: '1:165374914153:android:c662f8bc9ec673adf2fcf8',
    messagingSenderId: '165374914153',
    projectId: 'todo-app-project-e81a3',
    storageBucket: 'todo-app-project-e81a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1UN2aAiBYteuECbBwg3qy5bWjdzeE1Es',
    appId: '1:165374914153:ios:955a276572abf7d2f2fcf8',
    messagingSenderId: '165374914153',
    projectId: 'todo-app-project-e81a3',
    storageBucket: 'todo-app-project-e81a3.appspot.com',
    iosBundleId: 'com.example.todoAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1UN2aAiBYteuECbBwg3qy5bWjdzeE1Es',
    appId: '1:165374914153:ios:955a276572abf7d2f2fcf8',
    messagingSenderId: '165374914153',
    projectId: 'todo-app-project-e81a3',
    storageBucket: 'todo-app-project-e81a3.appspot.com',
    iosBundleId: 'com.example.todoAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6yzfr5TO8RrPHCsKH2PPaERnUFNsOfZA',
    appId: '1:165374914153:web:330eb3f7e6cf3c90f2fcf8',
    messagingSenderId: '165374914153',
    projectId: 'todo-app-project-e81a3',
    authDomain: 'todo-app-project-e81a3.firebaseapp.com',
    storageBucket: 'todo-app-project-e81a3.appspot.com',
    measurementId: 'G-P9HNXZ954Y',
  );
}
